version: '2'

services:

  sum:
    build: ./sum
    ports: ["5001:5000"]
  res:
    build: ./res
    ports: ["5002:5000"]
  mul:
    build: ./mul
    ports: ["5003:5000"]
  div:
    build: ./div
    ports: ["5004:5000"]
  
  app:
    build: ./app
    ports: ["5005:5000"]
    depends_on:
      - sum
      - res
      - mul
      - div
  client:
    build: ./client
    ports: ["5006:5000"]
    depends_on:
      - app
